version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"
    environment:
      TZ: '%YOUR_TZ_HERE%'
      WEBPASSWORD: '%YOUR_SECURE_PIHOLE_PASSWORD%'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - '%YOUR_CONFIGS_ROOT%/pihole/etc/pihole/:/etc/pihole/'
      - '%YOUR_CONFIGS_ROOT%/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d'
      - '%YOUR_CONFIGS_ROOT%/pihole/var/pihole.log:/etc/pihole.log'
      - '%YOUR_CONFIGS_ROOT%/pihole/resolv.conf:/etc/resolv.conf'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
