version: '2'

services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: '%YOUR_MYSQL_ROOT_PASSWORD%'
      MYSQL_USER: filerun
      MYSQL_PASSWORD: '%YOUR_MYSQL_ROOT_PASSWORD%'
      MYSQL_DATABASE: filerun
    volumes:
      - %YOUR_CONFIGS_ROOT%/volumes/filerun/db:/var/lib/mysql

  web:
    image: afian/filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: filerun
      FR_DB_PASS: '%YOUR_MYSQL_ROOT_PASSWORD%'
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "81:80"
    volumes:
      - %YOUR_CONFIGS_ROOT%/filerun/html:/var/www/html
      - %YOUR_STORAGE_ROOT%/Filerun/:/user-files
