version: "2"

services:
    server:
        image: gitea/gitea:1.15.0-rootless
        environment:
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=db:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=gitea
            - GITEA__database__PASSWD=gitea
        restart: always
        volumes:
            - %YOUR_STORAGE_ROOT%/Git:/var/lib/gitea
            - %YOUR_CONFIG_ROOT%/volumes/gitea:/etc/gitea  
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3000:3000"
            - "2222:2222"
        depends_on:
            - db

    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=gitea
            - POSTGRES_DB=gitea
        volumes:
            - %YOUR_CONFIG_ROOT%/gitea/db:/var/lib/postgresql/data
