version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=%YOUR_TZ_HERE%
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - %YOUR_CONFIGS_ROOT%/calibre:/config
      - %YOUR_STORAGE_ROOT%/Books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
